apiVersion: v1
kind: Service
metadata:
  name: logto
  labels:
    app: logto
spec:
  type: ClusterIP
  selector:
    app: logto
  ports:
    - name: core
      port: 3001
      targetPort: core
      protocol: TCP
    - name: admin
      port: 3002
      targetPort: admin
      protocol: TCP
