apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: test-develop

resources:
- ../../base

patches:
# Application patches
- path: patches/app/endpoints.yaml
- path: patches/app/ingress.yaml
  target:
    kind: Ingress
    name: logto

# Database cluster patches
- path: patches/database/cluster-resources.yaml

replacements:
# Sync hostnames to Ingress
- source:
    kind: ConfigMap
    name: logto-config
    fieldPath: data.CORE_HOSTNAME
  targets:
  - select:
      kind: Ingress
      name: logto
    fieldPaths:
    - spec.rules.0.host
    - spec.tls.0.hosts.0

- source:
    kind: ConfigMap
    name: logto-config
    fieldPath: data.ADMIN_HOSTNAME
  targets:
  - select:
      kind: Ingress
      name: logto
    fieldPaths:
    - spec.rules.1.host
    - spec.tls.0.hosts.1
