apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- db-migration-hook.yaml # PreSync Hook
- deployment.yaml
- service.yaml
- configmap.yaml
- ingress.yaml

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/name: logto-app
    app.kubernetes.io/component: application
