apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# Database layer
- database/cluster.yaml

# Application layer
- app/db-migration-hook.yaml # PreSync Hook
- app/deployment.yaml
- app/service.yaml
- app/configmap.yaml
- app/ingress.yaml

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/name: logto-app
