apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: test-develop

resources:
- ../../base

patches:
- path: patches/endpoints.yaml
- path: patches/ingress.yaml
  target:
    kind: Ingress
    name: logto

replacements:
# Sync hostnames to Ingress
- source:
    kind: ConfigMap
    name: logto-config
    fieldPath: data.CORE_HOSTNAME
  targets:
  - select:
      kind: Ingress
      name: logto
    fieldPaths:
    - spec.rules.0.host
    - spec.tls.0.hosts.0
  - select:
      kind: ConfigMap
      name: logto-config
    fieldPaths:
    - data.ENDPOINT
    options:
      delimiter: "://"
      index: 1
- source:
    kind: ConfigMap
    name: logto-config
    fieldPath: data.ADMIN_HOSTNAME
  targets:
  - select:
      kind: Ingress
      name: logto
    fieldPaths:
    - spec.rules.1.host
    - spec.tls.0.hosts.1
  - select:
      kind: ConfigMap
      name: logto-config
    fieldPaths:
    - data.ADMIN_ENDPOINT
    options:
      delimiter: "://"
      index: 1
