apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: test-develop

resources:
- ../../base

patches:
- path: patches/config.yaml
- path: patches/ingress.yaml
  target:
    kind: Ingress
    name: demo

replacements:
# Sync hostnames to Ingress
- source:
    kind: ConfigMap
    name: demo-config
    fieldPath: data.HOSTNAME
  targets:
  - select:
      kind: Ingress
      name: demo
    fieldPaths:
    - spec.rules.0.host
    - spec.tls.0.hosts.0
